### ISSUE TITLE
Evaluate IIIF Server

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#1]
- [x] @PlekszyGladz provides a test set of assets.
- [x] Evaluate an adapted Sever for the AMOS Use-Case providing https://iiif.io/ functionality.

**Comment by ktk** [comment]
Reference https://github.com/IIIF/awesome-iiif

**Comment by l00mi** [comment]
- 16h Evaluation

**Comment by l00mi** [comment]
@ktk checks with Quentin/Ludovic.

**Comment by ktk** [comment]
Requirements:

* Images
* PDF (not even sure if part of the spec)
* Video might come in the future, not a requirement right now though
* Annotations should be available in RDF (JSON-LD or alike)

**Comment by PlekszyGladz** [comment]
> * PDF (not even sure if part of the spec)

If possible, yes (mainly because of OCR-Fulltext)

**Comment by l00mi** [comment]
Uh, okay but here we need to be careful with the expectations. If there is Fulltext which we like to search, it definitely needs also to go to the RDF Store.

So lets also collect the requirements about __what__ we want to do with the PDF.

**Comment by PlekszyGladz** [comment]
Primarily there are 4 requirements for PDFs. I listed them by priority (from most to least important):

- Displaying images of PDF
- Searching OCR fulltext within one PDF document (as in a regular PDF reader)
- Copying and pasting text from the PDF
- Searching fulltext of all documents (while this is very desirable, I am aware that this may be non trivial)

**Comment by l00mi** [comment]
* Image API
  * Request Different Versions of the original Image (thumbnails, etc ...)
* Presentation API (Stateless)
  * JSON-LD documents (-> Linked Data)
  * Annotations (Boxes, Links)
  * Metadata

Most tools do support the Image API, Presentation API is use-case/domain specific.

IIIF Server: https://cantaloupe-project.github.io/ (Open Source)
* Caching Layer
* S3 compatible (a standard big file cloud storage protocol)
* Fast

**Comment by ktk** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/University_of_Illinois/NCSA_Open_Source_License) about the University of Illinois/NCSA Open Source License: Seems to be MIT/BSD like which is great. No restrictions according to Wikipedia.

**Comment by l00mi** [comment]
Example with text-overlay: https://mirador-textoverlay.netlify.app/
