### ISSUE TITLE
Create IIIF Presentation API Manifest

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#10]
- [x] Create Manifest (potentially from Records in Context)
- [x] Check how to import OCR in Manifest

**Comment by PlekszyGladz** [comment]
8h

**Comment by l00mi** [comment]
Methods to create Manifest
1. Generate triples for the manifest from PDF and TIFFS (mini pipeline from imageserver)
2. Generate triples from the Scope Pipeline (https://gitlab.zazuko.com/amos/amos)
3. Expose the manifest through a trifid handler.
