### ISSUE TITLE
Integrate date transformation in the pipeline

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#11]
- [x] Check and understand the date ArchScope format.
- [x] Integrate necessary steps in pipeline.

**Comment by l00mi** [comment]
16h

**Comment by l00mi** [comment]
For reference https://github.com/zazuko/alod-data/issues/1

**Comment by l00mi** [comment]
@ktk I can't find the description of the ArchScope Date "Schema" do you have it somewhere? (I remember a picture of all possible syntax.)

**Comment by ktk** [comment]
I uploaded a PDF description here: [datumsangaben_scope.pdf](https://github.com/zazuko/amos/files/5987848/datumsangaben_scope.pdf)

**Comment by magdasalatka** [comment]
This repo is empty. Which piplenie are we talking about?

**Comment by ktk** [comment]
@magdasalatka pipeline is here https://gitlab.zazuko.com/amos/amos
