### ISSUE TITLE
Check for correct mapping of languages in the pipeline.

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#12]
8h

**Comment by PlekszyGladz** [comment]
- At the moment the exported language string is mapped in XRM to `example:laguages`
- Multiple laguages can be inside a single string either delimitted by ` / ` or a line-break char (e.g. `Deutsch / Französisch / Englisch` or `Deutsch&#xaFranzösisch&#xaItalienisch`
- The goal is that each of these languages (as Class [rico:Language](https://www.ica.org/standards/RiC/RiC-O_v0-2.html#Language)) is linked to the respective Record via the Property [rico:hasOrHadLanguage](https://www.ica.org/standards/RiC/RiC-O_v0-2.html#hasOrHadLanguage)
-  I suggest the following URI for Languages: `"https://data.ptt-archiv.ch/archive/language/{0}"` with `language`

**Comment by ktk** [comment]
The output should look somewhat like this pseudo Turtle:

```turtle
<record123> rico:hasOrHadLanguage <deutsch> .

<deutsch> a rico:Language ;
  rico:name "Deutsch"@de ;
  rico:name "Allemand"@fr . 

<franzoesisch> a rico:Language ;
  rico:name "Französisch"@de .
```

**Comment by l00mi** [comment]
Adding test to finish. After this its merged and will be reflected in the data.

**Comment by ktk** [comment]
I merged this to dev. Can be tested

**Comment by PlekszyGladz** [comment]
Just checked it. Seems to work perfectly!
