### ISSUE TITLE
Create a SPARQL query to fetch image metadata

### ISSUE THREAD

**Issue by ktk** [zazuko/amos#14]
So we know what we have and how we can continue for the IIIF manifests.

**Comment by ktk** [comment]
1h

**Comment by PlekszyGladz** [comment]
An example of an Record with attached Images (via `rico:Instantiation`) can be found here: https://data.ptt-archiv.ch/archive/record/205575

**Comment by ktk** [comment]
We need to split the fileName see #16

**Comment by ktk** [comment]
WIP SPARQL Query: https://s.zazuko.com/HanFw

**Comment by l00mi** [comment]
solved in #16
