### ISSUE TITLE
Export AIS System

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#2]
- [x] Provide credentials and a space for a manual CSV Export of the AIS.
- [x] CSV export of AIS are provided by the customer to a private Repository.

**Comment by l00mi** [comment]
- 1h Set-Up GitLab and Exchange

**Comment by ktk** [comment]
@PlekszyGladz do we have some data already?

**Comment by l00mi** [comment]
Ready https://gitlab.zazuko.com/amos/amos

**Comment by PlekszyGladz** [comment]
I pushed the first exported CSV from the AIS here --> https://gitlab.zazuko.com/amos/amos/-/commit/b4b17141792d15154d3bf8adc97ce0d45dbe38a6 (on branch 'dev' because 'master' is protected)

**Comment by l00mi** [comment]
* Sprachen korrektes Mapping?
