### ISSUE TITLE
Possibility to create Lists from Search Results

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#25]
- Records can be added to a list of favourites by clicking a Button next to each search result. 
- Results can be filtered by favourites.
- Users can add additional information (for private use) to items in the favourites (like alternative Names for the record, page reference, small “exzerpt” = short description of the content).

**Comment by PlekszyGladz** [comment]
24h

**Comment by l00mi** [comment]
As a first step are the lists stored in the Users Browser in the localStorage. In a second which is dependent on a user login facility, this lists can be persisted on the server side.
