### ISSUE TITLE
Implement Library Data Pipeline

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#38]
- [x] Understand the fetching on a technical level.
- [x] What to transform and change in the data?
- [x] Check completeness of dump.
- [x] Integrate S3 data access.
8h

**Comment by ktk** [comment]
* The current state of the export will remain as is
* Item is missing, should be part of the export soon
* Minimal XML based pipeline that transforms the data to proper RDF
* Only post-processing step is for mapping the namespace IRIs into the proper domain

**Comment by PlekszyGladz** [comment]
@ktk IRIs should be post-processed as follows to match the patter in use with the archival data:
from `https://open-na.hosted.exlibrisgroup.com/alma/41SLSP_RBE/rda/entity/work/9956891840105527` 
to `https://data.ptt-archiv.ch/library/work/9956891840105527`

also i suggest a second post-processing step to link works with the swisscovery online catalogue: if the IDs of works are prefixed with `https://bsb.swisscovery.slsp.ch/permalink/41SLSP_RBE/1sb9ls8/alma` you receive the correct permalinks. 

So the example above would look something like this: 
`<work#9956891840105527> <rdfs:seeAlso> <https://bsb.swisscovery.slsp.ch/permalink/41SLSP_RBE/1sb9ls8/alma9956891840105527>.` (not 100% sure if `seeAlso` is the correct property though...)

**Comment by PlekszyGladz** [comment]
> * Item is missing, should be part of the export soon

On this matter SLSP-Support just replied as follows:

> unfortunately at the moment Ex Libris does not provide RDA/RDF exports that include the item level information. Their RDA/RDF output is still fairly limited, in part because it is an area still very much in development

@ktk so I guess the current export ist the best we can expect at the moment...

**Comment by l00mi** [comment]
Potentially @cristianvasquez could implement this step.

Short term @ktk will make a one shot publication.

**Comment by l00mi** [comment]
blockes https://github.com/zazuko/amos/issues/60

**Comment by ktk** [comment]
RDF/XML header needed to parse the data:

```xml
<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
            xmlns:dc="http://purl.org/dc/elements/1.1/"
            xmlns:rdac="http://rdaregistry.info/Elements/c/"
            xmlns:rdaw="http://rdaregistry.info/Elements/w/"
            xmlns:rdam="http://rdaregistry.info/Elements/m/"
            xmlns:rdae="http://rdaregistry.info/Elements/e/"
            >
<!-- add data here without the xml header and the <collection> tag -->
</rdf:RDF>
```

**Comment by ktk** [comment]
Ok loaded into a separate graph for now, manually:

```sparql
SELECT * 
FROM <http://example.org/amos/slsp>
WHERE {
    ?s ?p ?o
}
```

**Comment by ktk** [comment]
IRIs still need to be refactored, can be done once it's part of a pipeline

**Comment by l00mi** [comment]
@ktk please change the namespace to https://data.ptt-archiv.ch/library/<something> else we will not be able to show this entries with trifid, as they are not dereferencable. (Its needed if we click on an entry.)

**Comment by l00mi** [comment]
@ktk We will also need the dates properly extracted, else we can't show it on the timeline. They need to be added to the manifest like this
```
 ?manifest <http://www.w3.org/2006/time#hasBeginning> ?beginning.
 ?beginning <http://www.w3.org/2006/time#inXSDDate> ?resourcestart .
```

**Comment by ktk** [comment]
ok here we go:

https://data.ptt-archiv.ch/library/manifestation/9958748050105527

For anything else I need the pipeline first

**Comment by PlekszyGladz** [comment]
see also this problem with GND-Links: https://github.com/zazuko/amos/issues/60#issuecomment-999579973

**Comment by l00mi** [comment]
1 month periodicity -> write to a s3 bucket

@ludovicm67 @ktk define bucket and how to access for the upload and what filename(s) to use.

**Comment by ktk** [comment]
@ludovicm67 could you tell us where we can put these files? It should be a different folder than for the images, we propose to call it `datasource`. We will add the library and archive source files there (XML & CSV).

**Comment by ludovicm67** [comment]
I created a new S3 bucket called `amos-datasource`.
@PlekszyGladz should have access with the credentials I gave him last time.

Just make sure to upload files with a Public policy.
If you are using Minio client (`mc`), you can upload files using something similar:

```sh
mc cp \
  --attr x-amz-acl=public-read
  <local_file_path> \
  <storage_alias>/amos-datasource/<dest_file_path>
```

with:
- `<local_file_path>`: the local path to the file to upload
- `<storage_alias>`: the name you gave for the S3 endpoint
- `<dest_file_path>`: the complete path including the name of the file in the bucket

For information, I uploaded a file `test.txt` at the root of the bucket, and it's reachable using this URL: https://amos-datasource.fra1.digitaloceanspaces.com/test.txt
You can delete this file.

**Comment by PlekszyGladz** [comment]
@ktk i provided the source files for the pipeline in the newly created s3 bucket.

- Library Data: https://amos-datasource.fra1.digitaloceanspaces.com/slsp.xml
- Scope Data: https://amos-datasource.fra1.digitaloceanspaces.com/scope.csv

we will manage version of these files on our side, so these file names are permanent

**Comment by PlekszyGladz** [comment]
still todo:
- updating the barndard59 packages
- Library Pipeline (should parse proplerly by now)

**Comment by ktk** [comment]
Task update:

- [x] update barnard59 to latest 1.x release
- [x] Fetch data from S3
- [x] Refactor scope pipeline
- [x] Add swisscovery link
- [x] Fix GND IRI
- [x] Refactor IIIF pipeline
- [x] IIIF S3 images index (talk to @ludovicm67 )
- [x] Add SLSP pipeline
- [x] Upload data pipeline (q: graph handling)
- [x] Refactor `.gitlab-ci` & merge branches properly

TODO:

- [ ] Implement #67 for IIIF
- [ ] UTF-Encoding in SLSP XML export
- [ ] SLSP date processing #78 
- [x] Graph handling: Scope, SLSP, IIIF, languages, museum?

**Comment by ktk** [comment]
Naming:
- archive
- library
- museum

For the rest, as fit
