### ISSUE TITLE
Define Namespace with Customer

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#4]
- [x] Define Namespace (e.g. data.*customer*.ch )
- [x] Customer adds Sub-Domain pointing with CNAME to ld.zazuko.com.

**Comment by l00mi** [comment]
- 2h Discussions

**Comment by l00mi** [comment]
@PlekszyGladz habt ihr hier schon eine Idee? Wollen hierzu ein kleines Meeting ansetzten, um die möglichen Varianten und damit verbunden Abklärungen aufzulisten?

**Comment by PlekszyGladz** [comment]
@l00mi @ktk am Besten scheint mir `data.ptt-archiv.ch` als Namespace zu sein. Die Domain gehört uns bereits, müssten aber bei der Subdomain noch den Alias-Eintrag machen.

**Comment by l00mi** [comment]
Gekauft! Bitte einen Eintrag mit CNAME von `data.ptt-archiv.ch` auf `data-ptt-archiv-ch.zazuko.net` veranlassen.

**Comment by l00mi** [comment]
@sandhose can you do the necessary on our side.

**Comment by l00mi** [comment]
Works https://data.ptt-archiv.ch/
