### ISSUE TITLE
Fix histogram component filter.

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#40]
The histogram component needs to be slightly changed that the filtering is working again because of the different attachement of time in the dataset.

4h

**Comment by l00mi** [comment]
@tpluscode can you give an estimate here for the next sprint?

**Comment by tpluscode** [comment]
This is only to adjust the query to get the correct patterns?

**Comment by l00mi** [comment]
The problem is that it is based on the "collected" filters from the HTML or in this case the SVG. So it would need to adapt the filter functionality to be able to have a second degree filter.

Before it was _Document -> Date_ now its _Document -> TimeObject -> Date_

**Comment by tpluscode** [comment]
I believe this is fixed now @l00mi
