### ISSUE TITLE
Export List

### ISSUE THREAD

**Issue by ktk** [zazuko/amos#41]
- The list can be exported and downloaded for use in different tools (.xlsx, .csv).

4h

**Comment by tpluscode** [comment]
Which exact information do we want exported?

cc @PlekszyGladz

**Comment by PlekszyGladz** [comment]
The main information to export should be:
1. rico:identifier
2. rico:name
3. rico:scopeAndContent
4. time:hasBeginning
5. time:hasEnd
6. and maybe the IRI of the record itself?

**Comment by l00mi** [comment]
Needs to be copied from base project.

**Comment by tpluscode** [comment]
@PlekszyGladz I added these columns to the exported csv. Let me know if the headers are fine

**Comment by PlekszyGladz** [comment]
@tpluscode seems fine to me except one thing: What ist the column "Code" for? In the test exports I did it was always empty...

**Comment by tpluscode** [comment]
Oh, it should not be there. Sorry. Removing

**Comment by l00mi** [comment]
Change titles to: 

Signature | Title | Description | Start date | End date | Permalink
-- | -- | -- | -- | -- | --
