### ISSUE TITLE
Deploy a separate DB Instance for MFK.

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#45]
On stardog free licence find a deployment option.

**Comment by l00mi** [comment]
@ludovicm67 can you ping me please on this issue.

**Comment by l00mi** [comment]
Current Idea:
- [x] On our jon Cluster deploy a Stardog Instance for PTT-Archive based one the Free Licence
- [ ] Adapt the Pipelines to use this new Stardog Instance and switch the current Trifid instance to use the new store.

@PlekszyGladz can you please create a Free Licence for the PTT-Archive with your contact details: https://www.stardog.com/get-started/ and share the licence with @ludovicm67 in Zulip ?

**Comment by l00mi** [comment]
@PlekszyGladz is it okay to use MFK in the naming of this store internally as it seem it will be used by other in the MFK later on?

**Comment by ludovicm67** [comment]
Waiting for the license file before deploying the new Stardog instance.

**Comment by PlekszyGladz** [comment]
> can you please create a Free Licence for the PTT-Archive with your contact details: https://www.stardog.com/get-started/ and share the licence with @ludovicm67 in Zulip ?

is done!

> is it okay to use MFK in the naming of this store internally as it seem it will be used by other in the MFK later on?

@l00mi MfK should be all right for internal purposes. If the naming is case sensitive i would use the official version (small 'f') though.

**Comment by ludovicm67** [comment]
I deployed the Stardog instance in the `jon` cluster using the license file provided by @PlekszyGladz.
I will configure it beginning of next week and configure the pipeline and the Trifid instance to use it instead of the actual one.

**Comment by l00mi** [comment]
@ludovicm67 please check the performance in regard of the histogram.

https://data.ptt-archiv.ch/search/new.html

**Comment by ludovicm67** [comment]
Using a CPU-optimized node for the Stardog instance help to have better performances.
If you want to improve performances more, someone else then me needs to update the SPARQL queries so that they are not dependent on the screen size and so that they can get cached properly.
