### ISSUE TITLE
Investigate Access of Library Data

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#5]
- [x] Get the data related to PTT-Archive from SLSP

- [ ] Investigate who the relevant Library Data as Linked Data can be either directly access or copied to endpoint from SLSP under customers control.

**Comment by PlekszyGladz** [comment]
- Records in SLSP from PTT-Archiv/MfK can be easily exported and donloaded from the SLSP-Backend as RDA/RDF
- RDF of the library data cannot be accessed directly and needs to be copied to the endpoint
- If needed, this can be automated later on (Export would be uploaded via FTP). But exports are anyways only be necessary a couple of times a year
- Example of exported records can be found in the following Gist: https://gist.github.com/PlekszyGladz/8e25247ea4f7b449234ef2899586c9fb

**Comment by l00mi** [comment]
* RDF/XML https://www.w3.org/TR/rdf-syntax-grammar/

**Comment by l00mi** [comment]
@PlekszyGladz Contacted SLSP, no answer yet.

**Comment by PlekszyGladz** [comment]
According to SLSP the "RDA/RDF" export is correct. But we are investigating further, if there are possibilities to properly export serialized RDF.
