### ISSUE TITLE
Change histogram filtering behaviour for records with intervals as creation dates

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#54]
Currently filtering dates seems to only select records where both the start and the end date are inside the specified interval.

As we have mandy records with large creation date intervals filtered results should include all records with any overlap to the filter. That is (start OR end date inside query interval ) OR (start date smaller than the query interval AND end date lager than the query interval)

**Comment by l00mi** [comment]
The histogram is now only filtering on the Start date.

**Comment by PlekszyGladz** [comment]
@l00mi Just checked it and seems to work fine.
But only filtering the Start Date still leaves out some cases. I made a small sketch showing a query (pink) and possible records below them (designated as A to F) 
![image](https://user-images.githubusercontent.com/5487333/146745842-7edb04e1-a7a8-494a-a6d9-49672d1c10e6.png)
Cases A to D should show up in the results. With the current setup we only have B and D. 
--> It seems the simplest ist to rule out all records where their end date is lower than the query start date or the start date is higher than the query end date. What do you think?
