### ISSUE TITLE
Translation of the Interface

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#57]
The Interface should be translated to German (for initial realease). In the future at least French (and maybe Italian and English) will be a requirement.

See screenshots with suggestions for the translation:
![digitalerlesesaal_translation_1](https://user-images.githubusercontent.com/5487333/145389995-14f500fe-8ef9-497a-beda-afb75a5d3ec5.png)
![digitalerlesesaal_translation_2](https://user-images.githubusercontent.com/5487333/145390021-c62b8088-5018-4352-9519-e9d6ffd1332a.png)

**Comment by l00mi** [comment]
@tpluscode  can you please take care of the remaining?
* The List Widget
  * Keine Liste, Liste, Persönliche Notizen, Notizen bearbeiten
* Select List
*Filter: list -> Liste:

**Comment by PlekszyGladz** [comment]
@tpluscode i found two last cases where the default list ("Starred") is not yet translated to "Rechercheliste". 
![image](https://user-images.githubusercontent.com/5487333/146926083-f322bdfa-144e-43c1-b405-af8ef2cf007d.png)
![image](https://user-images.githubusercontent.com/5487333/146926126-ec6c0e7e-11dc-4ca1-892e-75d1c3660ad5.png)
i tried to clear local storage but that did not help..
