### ISSUE TITLE
Ingress for http://pttarchiv.mfk.ch/

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#59]
Ingress which does simply redirect with the following rule:

Everything from
http://pttarchiv.mfk.ch/ -> to https://data.ptt-archiv.ch/search

EXCEPT
http://pttarchiv.mfk.ch/detail.aspx?ID=116
->
https://data.ptt-archiv.ch/archive/record/116

ergo
http://pttarchiv.mfk.ch/detail.aspx?ID=<*>
->
https://data.ptt-archiv.ch/archive/record/<*>

**Comment by ludovicm67** [comment]
Please CNAME pttarchiv.mfk.ch to `pttarchiv-mfk-ch.zazuko.net`

**Comment by l00mi** [comment]
@PlekszyGladz see above

**Comment by PlekszyGladz** [comment]
@l00mi and @ludovicm67 the new DNS entry will be active from Jan 1st.

**Comment by ludovicm67** [comment]
Thank you @PlekszyGladz for the CNAME.

Here are the results of some redirections:

  - http://pttarchiv.mfk.ch/other.ext -> https://data.ptt-archiv.ch/search/
  - http://pttarchiv.mfk.ch/other.ext?ID=116 -> https://data.ptt-archiv.ch/search/?ID=116
  - http://pttarchiv.mfk.ch/detail.aspx?ID=116 -> https://data.ptt-archiv.ch/archive/record/116
  - http://pttarchiv.mfk.ch/detail.aspx?id=116 -> https://data.ptt-archiv.ch/archive/record/116
  - http://pttarchiv.mfk.ch/detail.aspx?bad=1 -> https://data.ptt-archiv.ch/search/?bad=1
  - http://pttarchiv.mfk.ch/detail.aspx?bad=1&ID=116 -> https://data.ptt-archiv.ch/archive/record/116
  - http://pttarchiv.mfk.ch/toto -> https://data.ptt-archiv.ch/search/
  - http://pttarchiv.mfk.ch/ -> https://data.ptt-archiv.ch/search/
  - http://pttarchiv.mfk.ch -> https://data.ptt-archiv.ch/search/


Here is the script I used to get the above output:

```sh
#!/bin/sh

final_url () {
  res=$(curl -Ls -o /dev/null -w %{url_effective} "$1")
  echo "  - $1 -> ${res}"
}

final_url 'http://pttarchiv.mfk.ch/other.ext'
final_url 'http://pttarchiv.mfk.ch/other.ext?ID=116'
final_url 'http://pttarchiv.mfk.ch/detail.aspx?ID=116'
final_url 'http://pttarchiv.mfk.ch/detail.aspx?id=116'
final_url 'http://pttarchiv.mfk.ch/detail.aspx?bad=1'
final_url 'http://pttarchiv.mfk.ch/detail.aspx?bad=1&ID=116'
final_url 'http://pttarchiv.mfk.ch/toto'
final_url 'http://pttarchiv.mfk.ch/'
final_url 'http://pttarchiv.mfk.ch'
```

If it looks fine, you can close this issue.
