### ISSUE TITLE
Adapt Interface to also show Library data.

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#60]
- [x] Added the data, shows most fields.
- [x] Show the filter on top.
- [x] Show always PTT-Bibliothek on top of each entry?

**Comment by l00mi** [comment]
@PlekszyGladz okay first parts are online.

**Comment by l00mi** [comment]
Because of the missing interpreted dates they library data is not shown in the timeline.

**Comment by tpluscode** [comment]
@PlekszyGladz we will need data mapping to show library data in the redesigned details page

**Comment by PlekszyGladz** [comment]
@tpluscode what do you mean by data mapping. It will be hard/impossible to match the libary properties to the archive properties.  But I can give a minimal set of libary properties and their labels that should be shown in the detail view.

**Comment by tpluscode** [comment]
Yes please. That is more or less what I had in mind

**Comment by PlekszyGladz** [comment]
Ok, so here are the core elements for the first implementation:

![image](https://user-images.githubusercontent.com/5487333/146947600-f9d2e840-2079-4f55-9dae-44654cf6dcde.png)

- there is only one colored label on top that should read "Bibliothek"
- the first row should list all the creators of the work
- then the title of the work
- followed by the creationDate of the manifestation
- omit the scope and content, term of protection and the "Angaben zum Kontext" heading.
- then lastly in the table comes the publisher and placeOfPublication of the manifestation 

for everything else we will have to evaluate the library data more closely in january...

**Comment by tpluscode** [comment]
Ok, I updated the detail page to render library resources as requested. For example see https://data.ptt-archiv.ch/library/manifestation/9958772710105527

You will see that the creators are apparently not always mapped correctly from source dataset. This one was left as URI where I think it should be `Uri. Bauamt`?

**Comment by PlekszyGladz** [comment]
Thanks for the implementation! Looks good so far.

> You will see that the creators are apparently not always mapped correctly from source dataset. This one was left as URI where I think it should be Uri. Bauamt?

Exaclty, the correct creator would be `Uri. Bauamt`.
@ktk We should investigate the issue with URIs as part of the general library pipeline in #38. 
- The GND-Data is available as RDF (https://d-nb.info/gnd/1085918823/about/lds) 
- but the source from SLSP is not even using the proper permalinks (https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=1085918823 instead of https://d-nb.info/gnd/1085918823)

**Comment by PlekszyGladz** [comment]
@tpluscode Can we also add the blue "Bibliothek" label to the results in the search interface (analogous to the red archive hierarchy) without augmenting the dataset?

**Comment by l00mi** [comment]
@PlekszyGladz that information needs to come also from the data. I tried to add it ad-hoc in the query, but that is non-trivial unfortunately. We need to inject this information in the pipeline.

**Comment by PlekszyGladz** [comment]
Ok then we leave this for the first version. But we really should focus on the library data issues in the next year

**Comment by ktk** [comment]
@PlekszyGladz I guessed that SLSP IDs are numeric only but I find this: `https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=109042132X`

Is this a bug or a feature? As in, should I just accept anything as ID?

**Comment by ktk** [comment]
@PlekszyGladz also are you sure that GND IDs have the `/gnd/` part in there? I don't get anything back on that IRI, just when I remove `/gnd/`
