### ISSUE TITLE
Add context metadata

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#61]
Links to https://culture.ld.admin.ch/isil/CH-000525-4

rico:isOrWasHolderOf

**Comment by l00mi** [comment]
https://fedlex.data.admin.ch/eli/cc/1999/354

**Comment by PlekszyGladz** [comment]
> https://fedlex.data.admin.ch/eli/cc/1999/354

Not all records are mandated by this. so this would need some postprocessing in the pipeline...

**Comment by l00mi** [comment]
Okay, that was just a proposition, so no worries. The ISIL link is more important for now.

If you want or can do the post-processing at some point that would be a nice addition. So I propose to make a clearer issue for that in the Backlog and close this one?
