### ISSUE TITLE
properly render line breaks in metadata instead of "\n"

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#65]
- [x] Understand where in the pipeline or visualization the escaping is missing.
- [ ] Check if rendered in the Frontend.

8h

**Comment by PlekszyGladz** [comment]
Cases with "\n" instead of newlines: https://api.triplydb.com/s/VzE2dSXZ2

**Comment by ktk** [comment]
Replace `\n` with `\n` in a regex, that should probably work. Escaping is key

**Comment by PlekszyGladz** [comment]
needs to be reviewed in the store... @ktk
