### ISSUE TITLE
Add a filter for Entries which have Media

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#68]
A filter to add on top which can filter for everything which has Media

**Comment by tpluscode** [comment]
https://user-images.githubusercontent.com/588128/156550901-b76b090a-bb2b-448b-a443-1b044a429742.mp4

**Comment by PlekszyGladz** [comment]
works as intended and gets used a lot here ;)

but some users have problems, as they try to click the (unclickable) checkbox instead of the label. 

@tpluscode I propose changing it to a button similar to the other filters (i.e. remove the checkbox and add black border around the label).
