### ISSUE TITLE
Collection of slow queries

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#69]
**Main focus for improving performance: Search interface and listing of results**

Some general observations:
- ✓ Entering text queries and/or activating new filters shows the number of hits rather quickly (This even holds for a larger number of combined filters!)
- ✗ listing results takes too long
- ✗ listing results sometimes retriggers (without there being a new query/filter) 
- ✗ listing results sometimes shows wrong hits first and then quickly retriggers

**Second focus after First is improved: Detail page of records**
- ✗ takes some time to load the page itself, wich could be improved upon.
- ✓ viewer performance is very satisfactory

**Comment by PlekszyGladz** [comment]
@PlekszyGladz gives some usecases to extract slow queries.
@ktk runs profiler on queries

**Comment by PlekszyGladz** [comment]
@ktk can you give a short update here

**Comment by PlekszyGladz** [comment]
I updated the initial post with more information about what takes to long

**Comment by PlekszyGladz** [comment]
@l00mi @ktk @PlekszyGladz discuss the next possible steps here:
- elastic search?
- optimising queries? (maybe in coopeartion with stardog)
- beefier SPARQL-Endpoint
