### ISSUE TITLE
Setup integration environment

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#87]
Create an integration environment to test new features before deploying them to prod.

**Comment by ludovicm67** [comment]
Two instances:
- PROD: deployed on each SemVer tag ; URL: https://data.ptt-archiv.ch/
- INTEG: deployed on each commit on the `master` branch, no cache ; URL: https://data-ptt-archiv.zazukoians.org/

For INTEG we only need to push the data in the test database.
