### ISSUE TITLE
Records with no title

### ISSUE THREAD

**Issue by tpluscode** [zazuko/amos#91]
We found that there are some records which do not have a title: https://s.zazuko.com/7H43Jj

**Comment by PlekszyGladz** [comment]
I checked those records in scope and fixed the missing titles.
Once the new export is ready for the pipeline (probably tomorrow) this should be fixed.

**Comment by PlekszyGladz** [comment]
The verify step still fails (https://gitlab.zazuko.com/amos/amos/-/jobs/22430). But there are no records without titles anymore in the source CSV. Is the verify step checking the correct data? If I select https://data-ptt-archiv.zazukoians.org/query as the endpoint it does not have empty titles anymore: https://s.zazuko.com/g3zP5t
